from __future__ import annotations

import math

from botocore.config import Config

from rca_agent.config.settings import (
    LLM_DEFAULT_TIMEOUT_SECONDS,
    REMEDIATION_RESET_TIMEOUT_SECONDS,
    REMEDIATION_VERIFICATION_MAX_WAIT_SECONDS,
    S3_EVIDENCE_MAX_RETRIES,
)

AWS_SDK_CONNECT_TIMEOUT_SECONDS = 5
AWS_SDK_READ_TIMEOUT_SECONDS = 20
AWS_SDK_TOTAL_MAX_ATTEMPTS = 1

SIDE_EFFECT_AWS_CLIENT_CONFIG = Config(
    connect_timeout=AWS_SDK_CONNECT_TIMEOUT_SECONDS,
    read_timeout=AWS_SDK_READ_TIMEOUT_SECONDS,
    retries={
        "mode": "standard",
        "total_max_attempts": AWS_SDK_TOTAL_MAX_ATTEMPTS,
    },
)

if S3_EVIDENCE_MAX_RETRIES < 1:
    raise ValueError("S3_EVIDENCE_MAX_RETRIES must be a positive integer")

AWS_SDK_CALL_WORST_CASE_SECONDS = AWS_SDK_CONNECT_TIMEOUT_SECONDS + AWS_SDK_READ_TIMEOUT_SECONDS
NOTIFICATION_MAX_RETRIES = 3
NOTIFICATION_BASE_DELAY_SECONDS = 1.0
NOTIFICATION_BACKOFF_WORST_CASE_SECONDS = NOTIFICATION_BASE_DELAY_SECONDS * (2 ** (NOTIFICATION_MAX_RETRIES - 1) - 1)
NOTIFICATION_PUBLISH_WORST_CASE_SECONDS = (
    NOTIFICATION_MAX_RETRIES * AWS_SDK_CALL_WORST_CASE_SECONDS + NOTIFICATION_BACKOFF_WORST_CASE_SECONDS
)
EVIDENCE_SAVE_BASE_DELAY_SECONDS = 1.0
EVIDENCE_SAVE_BACKOFF_WORST_CASE_SECONDS = EVIDENCE_SAVE_BASE_DELAY_SECONDS * (2 ** (S3_EVIDENCE_MAX_RETRIES - 1) - 1)
EVIDENCE_SAVE_WORST_CASE_SECONDS = (
    S3_EVIDENCE_MAX_RETRIES * AWS_SDK_CALL_WORST_CASE_SECONDS + EVIDENCE_SAVE_BACKOFF_WORST_CASE_SECONDS
)
PLAYBOOK_SAVE_WORST_CASE_SECONDS = 2 * AWS_SDK_CALL_WORST_CASE_SECONDS
SIDE_EFFECT_SAVE_WORST_CASE_SECONDS = max(
    EVIDENCE_SAVE_WORST_CASE_SECONDS,
    PLAYBOOK_SAVE_WORST_CASE_SECONDS,
)

SIDE_EFFECT_LEASE_MIN_SECONDS = 120
SIDE_EFFECT_LEASE_SAFETY_MARGIN_SECONDS = 30
SIDE_EFFECT_LEASE_SECONDS = max(
    SIDE_EFFECT_LEASE_MIN_SECONDS,
    math.ceil(SIDE_EFFECT_SAVE_WORST_CASE_SECONDS + SIDE_EFFECT_LEASE_SAFETY_MARGIN_SECONDS),
)

if SIDE_EFFECT_LEASE_SECONDS <= SIDE_EFFECT_SAVE_WORST_CASE_SECONDS:
    raise RuntimeError("Side-effect lease must exceed the worst-case external save bound")

REMEDIATION_CLAIM_SAFETY_MARGIN_SECONDS = 60
REMEDIATION_EXECUTION_WORST_CASE_SECONDS = (
    REMEDIATION_RESET_TIMEOUT_SECONDS
    + REMEDIATION_VERIFICATION_MAX_WAIT_SECONDS
    + 2 * AWS_SDK_CALL_WORST_CASE_SECONDS
    + LLM_DEFAULT_TIMEOUT_SECONDS
    + AWS_SDK_CALL_WORST_CASE_SECONDS
)
REMEDIATION_CLAIM_SECONDS = math.ceil(
    REMEDIATION_EXECUTION_WORST_CASE_SECONDS + REMEDIATION_CLAIM_SAFETY_MARGIN_SECONDS
)

PUBLICATION_MARK_ATTEMPTS = 3
PUBLICATION_MARK_RETRY_DELAY_SECONDS = 0.05
PUBLICATION_LEASE_SAFETY_MARGIN_SECONDS = 30
PUBLICATION_WORST_CASE_SECONDS = (
    NOTIFICATION_PUBLISH_WORST_CASE_SECONDS
    + PUBLICATION_MARK_ATTEMPTS * AWS_SDK_CALL_WORST_CASE_SECONDS
    + (PUBLICATION_MARK_ATTEMPTS - 1) * PUBLICATION_MARK_RETRY_DELAY_SECONDS
)
PUBLICATION_LEASE_SECONDS = math.ceil(PUBLICATION_WORST_CASE_SECONDS + PUBLICATION_LEASE_SAFETY_MARGIN_SECONDS)

if REMEDIATION_CLAIM_SECONDS <= REMEDIATION_EXECUTION_WORST_CASE_SECONDS:
    raise RuntimeError("Remediation claim must exceed the worst-case execution bound")
if PUBLICATION_LEASE_SECONDS <= PUBLICATION_WORST_CASE_SECONDS:
    raise RuntimeError("Publication lease must exceed the worst-case publish bound")
