from __future__ import annotations

import os

SQS_QUEUE_URL = os.environ.get("SQS_QUEUE_URL", "")
SQS_POLL_WAIT_SECONDS = int(os.environ.get("SQS_POLL_WAIT_SECONDS", "20"))

DYNAMODB_TABLE_NAME = os.environ.get("DYNAMODB_TABLE_NAME", "")
SESSION_TTL_DAYS = int(os.environ.get("SESSION_TTL_DAYS", "90"))

S3_REPORT_BUCKET = os.environ.get("S3_REPORT_BUCKET", "")
SNS_NOTIFICATION_TOPIC_ARN = os.environ.get("SNS_NOTIFICATION_TOPIC_ARN", "")
S3_VECTOR_BUCKET_NAME = os.environ.get("S3_VECTOR_BUCKET_NAME", "")
S3_VECTOR_PLAYBOOK_INDEX = os.environ.get("S3_VECTOR_PLAYBOOK_INDEX", "playbook")
S3_VECTOR_REGION = os.environ.get("S3_VECTOR_REGION", "us-east-1")
BEDROCK_EMBEDDING_MODEL_ID = os.environ.get("BEDROCK_EMBEDDING_MODEL_ID", "cohere.embed-v4:0")

PRESIGNED_URL_EXPIRY = 86400

CC_TIMEOUT_SECONDS = int(os.environ.get("CC_TIMEOUT_SECONDS", "1800"))

ALARM_STALENESS_SECONDS = int(os.environ.get("ALARM_STALENESS_SECONDS", "1800"))

HEALTHCARE_SERVICE_HOST = os.environ.get("HEALTHCARE_SERVICE_HOST", "")
HEALTHCARE_ECS_CLUSTER_NAME = os.environ.get("HEALTHCARE_ECS_CLUSTER_NAME", "")
HEALTHCARE_ECS_SERVICE_NAME = os.environ.get("HEALTHCARE_ECS_SERVICE_NAME", "")
HEALTHCARE_RDS_INSTANCE_IDENTIFIER = os.environ.get("HEALTHCARE_RDS_INSTANCE_IDENTIFIER", "")
HEALTHCARE_RESET_TIMEOUT_SECONDS = min(
    max(int(os.environ.get("HEALTHCARE_RESET_TIMEOUT_SECONDS", "10")), 1),
    30,
)
CLOUDWATCH_VERIFY_ATTEMPTS = min(max(int(os.environ.get("CLOUDWATCH_VERIFY_ATTEMPTS", "5")), 1), 5)
CLOUDWATCH_VERIFY_INTERVAL_SECONDS = min(
    max(int(os.environ.get("CLOUDWATCH_VERIFY_INTERVAL_SECONDS", "30")), 0),
    30,
)
_CLOUDWATCH_VERIFY_WAIT_SECONDS = (CLOUDWATCH_VERIFY_ATTEMPTS - 1) * CLOUDWATCH_VERIFY_INTERVAL_SECONDS
_MIN_SIDE_EFFECT_LEASE_SECONDS = HEALTHCARE_RESET_TIMEOUT_SECONDS + _CLOUDWATCH_VERIFY_WAIT_SECONDS + 30
SIDE_EFFECT_LEASE_SECONDS = min(
    max(
        int(
            os.environ.get(
                "SIDE_EFFECT_LEASE_SECONDS",
                str(_MIN_SIDE_EFFECT_LEASE_SECONDS),
            )
        ),
        _MIN_SIDE_EFFECT_LEASE_SECONDS,
    ),
    300,
)

ENGINE = "cc-headless"
